search_api.processor.plugin.search_api_rendered_item:
  type: mapping
  label: 'Rendered item processor configuration'
  mapping:
    view_mode:
      type: sequence
      label: 'The selected view modes'
      sequence:
        - type: string
          label: 'A view mode'
    roles:
      type: sequence
      label: 'The selected roles'
      sequence:
        - type: string
          label: 'A role'
search_api.processor.plugin.node_status:
  type: mapping
  label: 'Node status processor configuration'
search_api.processor.plugin.stopwords:
  type: mapping
  label: 'Stopwords processor configuration'
  mapping:
    fields:
      type: sequence
      label: 'The selected fields'
      sequence:
        - type: string
          label: 'Selected field'
    file:
      type: string
      label: 'The file path'
    stopwords:
      type: text
      label: 'Defined stopwords'
search_api.processor.plugin.tokenizer:
  type: mapping
  label: 'Tokenizer processor configuration'
  mapping:
    fields:
      type: sequence
      label: 'The selected fields'
      sequence:
        - type: string
          label: 'Selected field'
    spaces:
      type: string
      label: 'Regular expression for spaces'
    ignorable:
      type: string
      label: 'Regular expression for ignorables'
search_api.processor.plugin.transliteration:
  type: mapping
  label: 'Transliteration processor configuration'
  mapping:
    fields:
      type: sequence
      label: 'The selected fields'
      sequence:
        - type: string
          label: 'Selected field'
search_api.processor.plugin.search_api_language_processor:
  type: mapping
  label: 'Language processor configuration'
search_api.processor.plugin.ignorecase:
  type: mapping
  label: 'Ignore case processor configuration'
  mapping:
    fields:
      type: sequence
      label: 'The selected fields'
      sequence:
        - type: string
          label: 'Selected field'
search_api.processor.plugin.add_url:
  type: mapping
  label: 'Add URL processor configuration'
search_api.processor.plugin.search_api_content_access_processor:
  type: mapping
  label: 'Content access processor configuration'
search_api.processor.plugin.search_api_highlight_processor:
  type: mapping
  label: 'Highlight processor configuration'
  mapping:
    prefix:
      type: string
      label: 'Text/HTML that will be prepended to all occurrences of search keywords in highlighted text.'
    suffix:
      type: string
      label: 'Text/HTML that will be appended to all occurrences of search keywords in highlighted text.'
    excerpt:
      type: boolean
      label: 'When enabled, an excerpt will be created for searches with keywords, containing all occurrences of keywords in a fulltext field.'
    excerpt_length:
      type: integer
      label: 'The requested length of the excerpt, in characters.'
    highlight:
      type: string
      label: 'Select whether returned fields should be highlighted. (always/if returned/never).'
search_api.processor.plugin.search_api_role_filter_processor:
  type: mapping
  label: 'Role filter processor'
  mapping:
    fields:
      type: sequence
      label: 'The selected fields'
      sequence:
        - type: string
          label: 'The field name'
    default:
      type: boolean
      label: 'Default'
    roles:
      type: sequence
      label: 'The selected roles'
      sequence:
        - type: string
          label: 'The role name'
search_api.processor.plugin.search_api_html_filter_processor:
  type: mapping
  label: 'HTML filter processor'
  mapping:
    fields:
      type: sequence
      label: 'The selected fields'
      sequence:
        - type: string
          label: 'The field name'
    title:
      type: boolean
      label: 'Title'
    alt:
      type: boolean
      label: 'Alt'
    tags:
      type: text
      label: 'Tag boosts'
search_api.processor.plugin.search_api_add_aggregation_processor:
  type: mapping
  label: 'Add aggregation processor'